#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 10 21:54:50 2022

@author: kimsubin
"""

import sys
input = lambda: sys.stdin.readline()
print = lambda x: sys.stdout.write(str(x) + "\n")
from collections import deque


max_number = 100001
n, k = map(int, input().split())
visited = [0] * max_number

def bfs(v):
    q = deque([v])
    while q:
        v = q.popleft()
        if v == k:
            return visited[v]
        for i in (v-1, v+1, 2*v):
            if 0 <= i < max_number and not visited[i]:
                visited[i] = visited[v] + 1
                q.append(i)


print(bfs(n))