#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 10 22:41:37 2022

@author: kimsubin
"""

import sys
input = lambda: sys.stdin.readline()
print = lambda x: sys.stdout.write(str(x) + "\n")

n, d = map(int,input().split())
graph = [list(map(int, input().split())) for _ in range(n)]
distance = [i for i in range(d+1)]

for i in range(d+1):

    distance[i] = min(distance[i], distance[i-1]+1)

    # 지름길을 반복하여 최단 거리를 찾기
    for start, end, n_distance in graph:
        if i == start and end <= d and distance[i]+n_distance < distance[end]:
            distance[end] = distance[i]+n_distance


print(distance[d])