#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 18 23:33:43 2022

@author: kimsubin
"""

num = int(input())
for _ in range(num):
    target = list(input())
    tmp = [] 
    
    for x in target :
       if x == '(' :
        tmp.append(x)
       else:
          if len(tmp) == 0:
                tmp.append(x)
                break
          else: tmp.pop()

    if len(tmp) == 0:
        print("YES")
    else: print("NO")
    