#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 20 23:22:46 2022

@author: kimsubin
"""



while True:
    
    number = input()
    
    if number == "0" :
        break
    else:
        print( "yes" if number == number[::-1] else "no")