#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 21 15:24:58 2022

@author: kimsubin
"""


import sys
input = lambda: sys.stdin.readline().rstrip()
print = lambda x: sys.stdout.write(str(x) + "\n")

k, n = map(int, input().split())

lines = [int(input()) for _ in range(k)]

start, end = 1, max(lines) 

while start <= end: 
    mid = (start + end) // 2 
    count = 0 
    
    for i in lines:
        count += i // mid 
        
    if count >= n: 
        start = mid + 1
    else:
        end = mid - 1
print(end)