#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 26 20:31:04 2022

@author: kimsubin
"""


# 선형 탐색으로 하면 시간 초과
# 이진 탐색으로 풀이하기! 

import sys
input = lambda: sys.stdin.readline().rstrip()
print = lambda x: sys.stdout.write(str(x) + "\n")

n = int(input())
number = set(map(int, input().split()))

m = int(input())
x = list(map(int,input().split()))

for i in x:
    print("1" if i in number else "0")





