#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  5 21:49:36 2022

@author: kimsubin
"""
import sys
input = lambda: sys.stdin.readline().rstrip()
print = lambda x: sys.stdout.write(str(x) + "\n")

n=int(input())

array=[0]
dp = [0 for _ in range(n+1)]

for _ in range(n):
    array.append(int(input()))


if n==1:
    print(array[1])

else:
    
    dp[1] = array[1]
    dp[2] = array[1] + array[2]
    
    #점화식 풀이로~!
    for i in range(3,n+1):
        dp[i] = max(dp[i-3] + array[i-1], dp[i-2]) + array[i]

    print(dp[n])