#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 30 23:18:15 2022

@author: kimsubin
"""

import sys
from collections import deque
input = lambda: sys.stdin.readline().rstrip()
print = lambda x: sys.stdout.write(str(x) + "\n")

n = int(input())
q = deque(enumerate(map(int, input().split())))
array = []

while q:
    index, paper = q.popleft()
    array.append(index + 1)

    if paper > 0:
        q.rotate(-(paper - 1))
    elif paper < 0:
        q.rotate(-paper)

print(' '.join(map(str, array)))